mikesart/gpuvis

- src/gpuvis.cpp
- src/gpuvis_graph.cpp
- src/gpuvis_utils.cpp
The <functional> include is no longer implicitly included by other includes, hence it needs to be explicitly included where it is being used.
Fixes #5
> Fix includes for GCC 7

- src/gpuvis.cpp
These two were discovered through clang's scan-build. I don't know if they can be triggered in the real world since they do appear to rely on certain GUI states which a human may not be able to trigger.
> Fix some potential null pointer dereferences

- sample/gpuvis_trace_utils.h
If using a >= C++11 compatible compiler, use thread_local instead of
__thread. This fixes a compilation error with Clang that doesn't provide
GCC's __thread.
Note: Alternatively, if you'd prefer `__thread` over `thread_local`, we could also only use `thread_local` for Clang.
> gpuvis_trace_utils: Prefer C++11 thread_local vs. __thread

- sample/gpuvis_trace_utils.h
Fixes linker error
"undefined reference to `gpuvis_gettime_u64'"
> gpuvis_trace_utils: Add 'static' to gpuvis_gettime_u64

- src/etl_utils.h
- src/gpuvis_etl.cpp
Only the gfx timeline is supported. I need to investigate more to
figure out how compute is handled.
Pre-emption is not handled correctly either.
The events emulate amgpu linux events to get the graph going in a
quick and dirty fashion.
> Support for ETL gpu events

- .editorconfig
- src/gpuvis.cpp
- src/gpuvis_etl.cpp
The output should now correctly match the gpuview output
> Fixups for the ETL parser

- src/gpuvis_etl.cpp
To compile the read_etl_file stub on non-windows os certain headers need
to get included.
> Include headers for stub compilation

- sample/glxgears.c
- sample/gpuvis_trace_utils.h
This PR ports the `GPUVIS_TRACE_BLOCK(F)` to C, with the help of some GNU extensions. I am using this in our project (which is mostly C), thought it might be useful to others. You can find details in the commit messages.
I tested this on Linux with C and C++, GCC 8 and Clang 8, also with `GPUVIS_TRACE_UTILS_DISABLE=1`. Looking forward to your feedback!
> Trace block macro c

- src/gpuvis.cpp
- src/gpuvis.h
- src/gpuvis_graph.cpp
- src/gpuvis_utils.cpp
- src/gpuvis_utils.h
- src/trace-cmd/trace-read.cpp
- src/trace-cmd/trace-read.h
This (work-in-progress) PR implements the use of more accurate vblank timestamps, as suggested in #30 :
It requires a small kernel patch (submitted to the mailing list [here](https://lists.freedesktop.org/archives/dri-devel/2019-August/230424.html)), that extends the `drm_vblank_event` with two fields: `time` holding a monotonic clock timestamp, and `high_prec`, a boolean indicating whether or not the timestamp came from a DRM driver that is able to generate HW-corrected high-precision vblank timestamps, or not.
GPUVis is fully backwards-compatible to how it worked before. High-precision vblank timestamps are only used in GPUVis if the following is true:
- the overall trace was created with monotonic clock (see below)
- the user turned ON the option to use high-prec timestamps …
> Use high-precision vblank timings, if available

- CMakeLists.txt
- sample/trace-cmd-capture.sh
- sample/trace-cmd-command.sh
- sample/trace-cmd-setup.sh
- sample/trace-cmd-start-tracing.sh
- sample/trace-cmd-stop-tracing.sh
- src/gpuvis.cpp
- src/gpuvis.h
- src/gpuvis_colors.inl
- src/gpuvis_etl.cpp
- src/gpuvis_ftrace_print.cpp
- src/gpuvis_graph.cpp
- src/gpuvis_graphrows.cpp
- src/gpuvis_i915_perfcounters.cpp
- src/i915-perf/i915-perf-read.cpp
- src/i915-perf/i915-perf-read.h
- src/trace-cmd/trace-read.cpp
- src/trace-cmd/trace-read.h
This PR is making use of the small optional library & recording tool coming off IGT (https://gitlab.freedesktop.org/drm/igt-gpu-tools) and helps showing some data generated by Intel's Gen observation architecture.
This adds essentially 2 new things : 
* a new row tracking the GPU utilization
* a panel showing the details about a given GPU timeline item
It's a first stab at showing that data into GPUVis. A lot more could be added but we have to start somewhere :)
I've tried to make this optional code so that there is no hard requirement on IGT.
It works with this IGT branch : https://github.com/djdeath/intel-gpu-tools/tree/review/i915-perf-tools
Just posted for review.
A couple of screenshots :
> Integrate i915-perf data into GPUvis

- src/gpuvis.cpp
- src/gpuvis.h
- src/gpuvis_graphrows.cpp
Import generic drm scheduler events in to AMD timelime.
DRM scheduler is based on AMD scheduler, so the semantics are mostly the
same.
Signed-off-by: Robert Beckett <bob.beckett@collabora.com>
> Add support for importing generic DRM sched timing events.

- src/gpuvis_graphrows.cpp
Having this empty row for captures done on AMD or when i915-perf
support disabled doesn't make sense.
Signed-off-by: Lionel Landwerlin <lionel.g.landwerlin@intel.com>
> Hide intel GPU generated event row when we don't have any

- sample/trace-cmd-start-tracing.sh
- src/gpuvis.cpp
- src/gpuvis.h
A trivial fix in the script and a rework of the color selection for i915-perf events.
> I915 perf updates

- sample/trace-cmd-capture.sh
- sample/trace-cmd-start-tracing.sh
- sample/trace-cmd-stop-tracing.sh
When executing one of the other scripts run trace-cmd-status.sh from the
location of this script. This way it is of no influence if the current
working directory is different.
There is a common way to put the script location into an environment variable
what is done here.
> Run trace-cmd-status.sh script from scripts location

- src/trace-cmd/trace-read.cpp
Log the error instead. Otherwise gpuvis stops working if trace-cmd-git
gets updated.
> Don't die() when an unknown trace-cmd options is encountered

- src/gpuvis_i915_perfcounters.cpp
With USE_I915_PERF=1, if the user opens a .dat file without a
.i915-dat one, we run into a segfault... Oopsie
> Don't try to access i915-perf data if no file was given

- src/gpuvis.cpp
- src/gpuvis.h
- src/gpuvis_graph.cpp
- src/gpuvis_graphrows.cpp
- src/gpuvis_i915_perfcounters.cpp
- src/gpuvis_plots.cpp
- src/i915-perf/i915-perf-read.cpp
- src/i915-perf/i915-perf-read.h
i915-perf reports generated by the GPU carry frequency information, we can just extract that and plot it (reusing the existing plotting code)
> i915-perf: add GPU frequency plot

- src/trace-cmd/trace-read.cpp
Do not subtract `min_file_ts` when assigning the high-prec vblank
timestamp.
This fixes a regression of high-prec vblank TS not showing up,
introduced by 93f2f67f963e8ea8e42c2199fa43c97477d409fd
> trace-read: Fix high-prec vblank timestamps

- src/gpuvis.cpp
- src/gpuvis_colors.inl
- src/gpuvis_i915_perfcounters.cpp
By default we're currently using the same color for all GPU timeline
events. But some i915 driver versions don't have tracepoint support to
build correlation back to the process that submitted the work, so that
we can use the process' color.
So just assign a default color so that we can at least tell items
apart on the timeline.
> i915-perf: set a different default colors to GPU timeline events

- meson.build
AFAICS this is used nowhere within this project, remove the dependency.
Signed-off-by: Rouven Czerwinski <rouven@czerwinskis.de>
> meson: remove python2

- .gitignore
- CMakeLists.txt
- Makefile
- README.md
- patches/0001-perf-data-Add-JSON-export.patch
- src/gpuvis.cpp
- src/gpuvis.h
This adds support for loading up a perf trace in JSON format.
Linux perf is a profiling tool that does CPU sampling. It's part of the Linux kernel. The goal of this work is to add support to gpuvis to show perf samples alongside a GPU trace so you can see both CPU and GPU events in sync.
I've added support to Linux perf for exporting a trace to JSON. This allows transferring the data over to gpuvis on Windows. The patch is merged in the Linux 5.13 kernel. For earlier kernel versions you have to patch perf manually.  The patch is included in this PR in the patches/ folder.
This code loads up the exported perf trace and shows the results in gpuvis.  Currently it just shows each sample as an instantaneous event. Later on we can add support for showing a histogram of samples, timeboxing them, …
> Add loading of Linux perf JSON

- src/gpuvis.cpp
- src/gpuvis.h
- src/gpuvis_graph.cpp
- src/gpuvis_i915_perfcounters.cpp
Some recent (probably a couple of years :() changes in i915 have made the tracking of GPU generated data to tracepoint a bit different.
Here are a couple of commits to resolve that issue without breaking the correlation on older kernels.
> Better i915-perf / tracepoint tracking

- src/gpuvis.cpp
- src/gpuvis.h
This patchset simplifies and expands existing zip file opening capabilities by removing unnecessary platform specific code, adding the ability to open archives containing more than one trace file, and performing cleanup of generated temporary files once they are no longer needed.
> Improve archive handling

- Makefile
- gpuvis.desktop
- gpuvis.metainfo.xml
Added .desktop file and appdata files to enable it as a shortcut
for easy launch from Linux desktop when installed as an RPM package
Update Makefile to support building on ppc64le arch
Signed-off-by: Dorinda Bassey <dbassey@redhat.com>
> Enable Shortcut for gpuvis Desktop Application

- Makefile
- meson.build
- meson_options.txt
This RapidJSON dependency added in the Meson Build is needed for loading
of Linux perf JSON. see reference - https://github.com/mikesart/gpuvis/pull/64
Signed-off-by: Dorinda Bassey <dbassey@redhat.com>
> Add RapidJSON dependency in Meson BuildSystem

- CMakeLists.txt
- Makefile
- meson.build
This makes the meson build up to date with the rest, and also stop downloading rapidjson from the web and get it from the system like other libs.
tbh why is there 3 build system?
> fix build using meson and not vendor rapidjson

- sample/trace-cmd-start-tracing.sh
- src/gpuvis.cpp
- src/gpuvis_graph.cpp
- src/i915-perf/i915-perf-read.cpp
A bunch of updates are included here
1) Fix crashes on some corner cases by adding additional checks
2) Use the timestamp API exposed by perf library
3) Enable scripts to select specific OA units
> Update i915 specific support for GPUvis

- src/gpuvis_ftrace_print.cpp
The key with which we add them is not just event.seqno, so we shouldn't use just seqno for deletion either.
Fixes begin/end events when we reuse the context ids on a thread. That way I can e.g. just use stackdepth.
> Actually delete the correct keys after processing a begin/end event.

- src/gpuvis_macros.h
Fixes errors such as:
In file included from ../src/stlini.cpp:61:
../src/gpuvis_macros.h:200:26: error: ‘uint64_t’ has not been declared
200 |     const char *findstr( uint64_t hashval );
|                          ^~~~~~~~
../src/gpuvis_macros.h:202:5: error: ‘uint64_t’ does not name a type
202 |     uint64_t getu64( const char *str, size_t len = ( size_t )-1 );
|     ^~~~~~~~
../src/gpuvis_macros.h:30:1: note: ‘uint64_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
29 | #include "../sample/gpuvis_trace_utils.h"
+++ |+#include <cstdint>
30 |
> Include <cstdint> in gpuvis_macros.h

- CMakeLists.txt
- Makefile
- meson.build
- sample/Makefile
- src/gpuvis_macros.h
- src/libtraceevent/include/linux/compiler.h
- src/libtraceevent/src/event-parse.c
- src/trace-cmd/trace-read.cpp
BSD support is similar to macOS: actual tracing isn't implemented but one can still view existing traces (like [amdgpu_trace.zip](https://github.com/mikesart/gpuvis/blob/master/traces/amdgpu_trace.zip) in this repo). Tested under Sway after building on
```
$ c++ --version
FreeBSD clang version 16.0.6 (https://github.com/llvm/llvm-project.git llvmorg-16.0.6-0-g7cbf1a259152)
Target: x86_64-unknown-freebsd14.0
Thread model: posix
InstalledDir: /usr/bin
```
> Unbreak build on FreeBSD

- CMakeLists.txt
- meson.build
- sample/trace-cmd-capture.sh
- sample/trace-cmd-setup.sh
- sample/trace-cmd-start-tracing.sh
- sample/trace-cmd-stop-tracing.sh
- src/gpuvis.cpp
- src/gpuvis.h
- src/gpuvis_graph.cpp
- src/gpuvis_graphrows.cpp
- src/gpuvis_i915_perfcounters.cpp
- src/i915-perf/i915-perf-read.cpp
- src/i915-perf/i915-perf-read.h
Add support for perf traces from the new Intel Xe driver. This requires linking with the new 'xe-oa' IGT library, similar to the previous 'i915-perf' library. Exported symbols from 'xe-oa' lib are in a different namespace from 'i915-perf' lib, allowing gpuvis to call into both libraries.
The traces from Xe driver are collected using 'xe-perf-recorder' tool (similar to 'i915-perf-recorder' tool). To start collection `export USE_XE_PERF=1`.
Overall, presentation of perf traces from Xe KMD in gpuvis is considered a subset of the i915 perf functionality. So Xe code paths in gpuvis reuse i915 code paths, except they call into the 'xe-oa' library rather than the 'i915-perf' library. So gpuvis is compiled with 'use_i915_perf' option as with i915-perf.
This pull request is based on the IGT …
> Add support for perf traces from Intel Xe driver

- src/gpuvis.cpp
- src/trace-cmd/trace-read.cpp
The code that handled msm events failed to set `id_start` and `user_comm` correctly which caused the wrong command name to appear in the timeline and sw and hw queue to incorrectly look identical.
Handle those similarly to how they are handled for AMD.
> Fix msm events handling

- src/trace-cmd/trace-read.cpp
All msm events that started with `msm_gpu_submit` where incorrectly being flagged as `TRACE_FLAG_SW_QUEUE`.
Remove this code since events are tagged anyway elsewhere.
This fixes the graph tooltip incorrectly reporting SW queue duration three times.
> Remove code incorrectly flagging msm events

- src/gpuvis.cpp
- src/trace-cmd/trace-read.cpp
- src/trace-cmd/trace-read.h
This PR enables parsing of events that occur in the kernel, but wish to be parsed using the same style as the events that are generated from userspace (e.g. by writing to `/sys/kernel/tracing/trace_marker`).  Because they originate from the kernel, these events have the benefit of being able to use the `bprint` format which is significantly more efficient on-disk, as constant strings can be interned.  These events are currently being generated with a `system` of `gpuvis`, making them easy to distinguish from any other event in the trace record.
Ideally, we would more intelligently collect information from the more structured `bprint` format, however for now it's easier to re-use the parsing infrastructure used on `print` format entries.  Therefore, we manually synthesize a `buf` field by …
> Add `gpuvis_print` event parsing

- src/gpuvis.cpp
- src/gpuvis.h
- src/gpuvis_graph.cpp
The swapper process has pid 0 across all cores, but we always want to be looking for the previous event on the current core only. This corrects the duration and thus, visualization of the swapper process.
I'm not entirely sure whether the performance of a linear scan will be prohibitive here, this was just the dumbest fast solution, and also I think this change probably warrants some small UI tweaks to de-emphasize the swapper zones, since they look a bit noisy this way...
edit: Added a simple commit which skips the background and comm text for swapper regions. Not sure what other people's vibes are here, but I like it personally.
> Fix calculation of swapper process durations

- src/gpuvis_graphrows.cpp
Newer VCN engines switched to a unified video encoder/decoder queue. This change adds support to display the new queue type.
> Add AMD VCN unified queue support

- sample/trace-cmd-setup.sh
- sample/trace-cmd-start-tracing.sh
xe-perf-recorder command line has been changed to use the OA unit id rather than engine class/instance to identify the OA unit for Xe OA data capture. Change gpuvis scripts to reflect that change.
> intel/xe: Change xe-perf-recorder command line
